### ISSUE TITLE
container_name with variables

### ISSUE THREAD

**Issue by pyToshka** [tuffk/Logstash-output-to-Azure-Blob#38]
Hi, i'm tried to configure container_name with variable in name for example %{+yyyy-MM-dd} 
Unfortunately i got error 
```
logstash_1       | [2020-12-30T09:13:16,012][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<URI::InvalidURIError: bad URI(is not URI?): https://ddd.blob.core.windows.net/logs-%{+yyyy-MM-dd}>, :backtrace=>["uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/rfc3986_parser.rb:67:in `split'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/rfc3986_parser.rb:73:in `parse'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/uri/common.rb:237:in `parse'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-core-0.1.15/lib/azure/core/service.rb:40:in `generate_uri'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-0.7.10/lib/azure/blob/blob_service.rb:1422:in `container_uri'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/azure-0.7.10/lib/azure/blob/blob_service.rb:111:in `create_container'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-azure-2.1.0/lib/logstash/outputs/azure.rb:213:in `blob_container_resource'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-azure-2.1.0/lib/logstash/outputs/azure.rb:129:in `register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:131:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:68:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:585:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"], "pipeline.sources"=>["/usr/share/logstash/pipeline/logstash.conf"], :thread=>"#<Thread:0x5f20765e@/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:54 run>"}

```
Is it possible to create container from plugin with variable  in name like 
```
          container_name => "logs-s%{+YYYY-MM-dd}"

```

**Comment by woodtechie1428** [comment]
@tuffk - This would be a great enhancement to add.
